version: 2
jobs:
  test:
    working_directory: ~/sharky-lodash
    docker:
      - image: circleci/node:11.2.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Install dependencies
          command: 'npm install'
      - run:
          name: Unit tests
          command: time npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  setup_and_test:
    jobs:
      - test
